
/**************************************************************
 *	
 *	powerupsfx, 8 bit, 11025Hz,
 *	1 channel, 10149 bytes/channel
 *	Total Size: 1 * 10149 + 4 (header) = 10193 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\So-mi\Desktop\soundlabassets\powerupsfx.wav
 *	Time-stamp: Wed Oct 12 16:30:21 2011
 *	
 **************************************************************/

#ifndef __POWERUPSFXH__
#define __POWERUPSFXH__

#define POWERUPSFXFREQ 11025
#define POWERUPSFXLEN 10149

extern const unsigned char powerupsfx[10149];

#endif /* __POWERUPSFXH__ */
