
/**************************************************************
 *	
 *	Snd_GameOver, 8 bit, 44100Hz,
 *	1 channel, 525312 bytes/channel
 *	Total Size: 1 * 525312 + 4 (header) = 525356 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_GameOver.wav
 *	Time-stamp: Mon Nov 05 01:44:52 2012
 *	
 **************************************************************/

#ifndef __SND_GAMEOVERH__
#define __SND_GAMEOVERH__

#define SND_GAMEOVERFREQ 44100
#define SND_GAMEOVERLEN 525312

extern const unsigned char Snd_GameOver[525312];

#endif /* __SND_GAMEOVERH__ */
