
/**************************************************************
 *	
 *	Snd_Sword, 8 bit, 44100Hz,
 *	1 channel, 84096 bytes/channel
 *	Total Size: 1 * 84096 + 4 (header) = 84140 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_Sword.wav
 *	Time-stamp: Mon Nov 05 01:44:59 2012
 *	
 **************************************************************/

#ifndef __SND_SWORDH__
#define __SND_SWORDH__

#define SND_SWORDFREQ 44100
#define SND_SWORDLEN 84096

extern const unsigned char Snd_Sword[84096];

#endif /* __SND_SWORDH__ */
