
/**************************************************************
 *	
 *	Snd_Scorpio, 8 bit, 44100Hz,
 *	1 channel, 40320 bytes/channel
 *	Total Size: 1 * 40320 + 4 (header) = 40364 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_Scorpio.wav
 *	Time-stamp: Mon Nov 05 01:44:56 2012
 *	
 **************************************************************/

#ifndef __SND_SCORPIOH__
#define __SND_SCORPIOH__

#define SND_SCORPIOFREQ 44100
#define SND_SCORPIOLEN 40320

extern const unsigned char Snd_Scorpio[40320];

#endif /* __SND_SCORPIOH__ */
