
/**************************************************************
 *	
 *	Snd_Level1, 8 bit, 22050Hz,
 *	1 channel, 233280 bytes/channel
 *	Total Size: 1 * 233280 + 4 (header) = 233324 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_Level1.wav
 *	Time-stamp: Sun Nov 04 06:25:10 2012
 *	
 **************************************************************/

#ifndef __SND_LEVEL1H__
#define __SND_LEVEL1H__

#define SND_LEVEL1FREQ 22050
#define SND_LEVEL1LEN 233280

extern const unsigned char Snd_Level1[233280];

#endif /* __SND_LEVEL1H__ */
