
/**************************************************************
 *	
 *	Snd_Start, 8 bit, 22050Hz,
 *	1 channel, 165312 bytes/channel
 *	Total Size: 1 * 165312 + 4 (header) = 165356 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_Start.wav
 *	Time-stamp: Sun Nov 04 06:15:07 2012
 *	
 **************************************************************/

#ifndef __SND_STARTH__
#define __SND_STARTH__

#define SND_STARTFREQ 22050
#define SND_STARTLEN 165312

extern const unsigned char Snd_Start[165312];

#endif /* __SND_STARTH__ */
