
/**************************************************************
 *	
 *	Snd_Knife, 8 bit, 44100Hz,
 *	1 channel, 78336 bytes/channel
 *	Total Size: 1 * 78336 + 4 (header) = 78380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_Knife.wav
 *	Time-stamp: Wed Nov 28 14:32:32 2012
 *	
 **************************************************************/

#ifndef __SND_KNIFEH__
#define __SND_KNIFEH__

#define SND_KNIFEFREQ 44100
#define SND_KNIFELEN 78336

extern const unsigned char Snd_Knife[78336];

#endif /* __SND_KNIFEH__ */
