
/**************************************************************
 *	
 *	Snd_TheEnd, 8 bit, 48000Hz,
 *	1 channel, 696960 bytes/channel
 *	Total Size: 1 * 696960 + 4 (header) = 697004 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Usuario\Desktop\gbaSound\Snd_TheEnd.wav
 *	Time-stamp: Wed Nov 28 17:12:30 2012
 *	
 **************************************************************/

#ifndef __SND_THEENDH__
#define __SND_THEENDH__

#define SND_THEENDFREQ 48000
#define SND_THEENDLEN 696960

extern const unsigned char Snd_TheEnd[696960];

#endif /* __SND_THEENDH__ */
